##
## Makefile for rush_rpg in /home/closingin/documents/projects/epitech/rush_rpg
##
## Made by      Rémi WEISLINGER
## Login        weisli_r
##
## Started on   Sat May 10 00:22:03 2014 weisli_r
## Update       Sat May 10 00:23:32 2014 weisli_r
##

NAME = js_server
